version: 2.1

orbs:
  docker: circleci/docker@2.0.1

commands:

  configure-dockerhub:
    description: Configure Docker Hub access
    steps:
      - run:
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

jobs:

  build-amd64:
    parameters:
      directory:
        type: string
      tag:
        type: string
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - configure-dockerhub
      - run:
          name: Build and push Docker Image for x86
          working_directory: << parameters.directory >>
          command: |
            docker build -t << parameters.tag >>-amd64 .
            docker push << parameters.tag >>-amd64

  build-arm64:
    parameters:
      directory:
        type: string
      tag:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - configure-dockerhub
      - run:
          name: Build and push Docker Image for arm64
          working_directory: << parameters.directory >>
          command: |
            docker build -t << parameters.tag >>-arm64 .
            docker push << parameters.tag >>-arm64

  push-multiarch-image:
    parameters:
      tag:
        type: string
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - configure-dockerhub
      - run:
          name: Create and push manifest for multiarch
          command: |
            docker manifest create \
            << parameters.tag >> \
            --amend << parameters.tag >>-arm64 \
            --amend << parameters.tag >>-amd64
            docker manifest push << parameters.tag >>

workflows:
  build-publish-80:
    jobs:
      - build-amd64:
          directory: "8.0"
          tag: "docker-symfony:8.0"
      - build-arm64:
          directory: "8.0"
          tag: "docker-symfony:8.0"
      - push-multiarch-image:
          tag: "docker-symfony:8.0"
          requires:
            - build-arm64
            - build-amd64
  build-publish-80-rr:
    jobs:
      - build-amd64:
          directory: "8.0-rr"
          tag: "docker-symfony:8.0-rr"
      - build-arm64:
          directory: "8.0-rr"
          tag: "docker-symfony:8.0-rr"
      - push-multiarch-image:
          tag: "docker-symfony:8.0-rr"
          requires:
            - build-arm64
            - build-amd64
