version: 2.1

commands:

  configure-dockerhub:
    description: Configure Docker Hub access
      steps:
          - run:
            name: Docker login
            command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

jobs:

  build-x86:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - configure-dockerhub
      - run:
          name: Build and push Docker Image for x86
          working_directory: "8.0"
          command: |
            docker build -t dlxmedia/docker-symfony:8.0-x86 .
            docker push dlxmedia/docker-symfony:8.0-x86

  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - configure-dockerhub
      - run:
          name: Build and push Docker Image for arm64
          working_directory: "8.0"
          command: |
            docker build -t dlxmedia/docker-symfony:8.0-arm64 .
            docker push dlxmedia/docker-symfony:8.0-arm64

  push-multiarch-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - configure-dockerhub
      - run:
          name: Create and push manifest for multiarch
          working_directory: "8.0"
          command: |
            docker manifest create \
            dlxmedia/docker-symfony:8.0 \
            --amend dlxmedia/docker-symfony:8.0-arm64 \
            --amend dlxmedia/docker-symfony:8.0-x86
            docker manifest push dlxmedia/docker-symfony:8.0

workflows:
  build-publish:
    jobs:
      - build-x86
      - build-arm64
      - push-multiarch-image:
          requires:
            - build-arm64
            - build-x86
