version: 2.1
orbs:
  docker-buildx: sensu/docker-buildx@1.1.1
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    docker:
      - image: drpsychick/dind-buildx:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Prepare docker buildx
          command: |
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
            docker buildx inspect --bootstrap
      - run:
          name: Docker login
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
      - run:
          name: Build and push all platforms
          command: |
            docker buildx build --progress plain --platform linux/amd64,linux/arm64 \
            --build-arg PHP_VERSION=8.0 \
            --tag dlxmedia/docker-symfony:8.0 --push .

workflows:
  commit:
    jobs:
      - build-and-push


#workflows:
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.1"
#          dockerfile: "8.1/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.1'
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.0-rr"
#          dockerfile: "8.0-rr/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.0'
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.1-swoole"
#          dockerfile: "8.1-swoole/Dockerfile"
#          extra_build_args: ''
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: latest
#          dockerfile: "8.0/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.0'

