version: 2.1
orbs:
  docker-buildx: sensu/docker-buildx@1.1.1
  docker: circleci/docker@2.0.1
workflows:
  build_and_publish:
    jobs:
      - build-and-push-8.0:
          executor: docker/docker
            steps:
                - setup_remote_docker
                - checkout
                - docker-buildx/install
                - docker/check
                - docker/build:
                    cache_from: 'dlxmedia/docker-symfony:8.0'
                    image: dlxmedia/docker-symfony
                    dockerfile: "8.0/Dockerfile"
                    extra_build_args: '--platform linux/amd64,linux/arm64 --build-arg PHP_VERSION=8.0'
                - docker/push:
                    image: dlxmedia/docker-symfony
                    tag: "8.0"
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.1"
#          dockerfile: "8.1/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.1'
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.0-rr"
#          dockerfile: "8.0-rr/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.0'
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: "8.1-swoole"
#          dockerfile: "8.1-swoole/Dockerfile"
#          extra_build_args: ''
#      - docker/publish:
#          image: dlxmedia/docker-symfony
#          tag: latest
#          dockerfile: "8.0/Dockerfile"
#          extra_build_args: '--build-arg PHP_VERSION=8.0'

