#name: build docker image
#
#on:
#  push:
#
#jobs:
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Clone repository
#        uses: actions/checkout@v2
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@master
#        with:
#          platforms: all
#
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push - 8.0
#        uses: docker/build-push-action@v2
#        with:
#          builder: ${{ steps.buildx.outputs.name }}
#          context: 8.0/
#          platforms: linux/arm64
#          push: true
#          tags: dlxmedia/docker-symfony:8.0-arm64
